### ISSUE TITLE
Bad path orig/src/esu.lexc.xfst?

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-esu#1]
`No rule to make target 'orig/src/esu.lexc.xfst', needed by 'lexicon.cleanup.hfst'.`

**Comment by Trondtr** [comment]
This seems a bit tricky. The src/fst/Makefile.am says:

lexicon.cleanup.hfst: orig/src/esu.lexc.xfst
        $(AM_V_HXFST)$(HFST_XFST) -p -e "source $<" -e "save stack $@" -E "hyvästi" #"exit"

**Comment by snomos** [comment]
Fixed in https://github.com/giellalt/lang-esu/commit/4ffd4d233c1e03de495762e6a5beb98958f7b794 et al.

**Comment by snomos** [comment]
Apparently not.
